// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCESl3dtJCTXM8UG3TWLXcNKCBHTD_F4P4',
    appId: '1:797515232441:web:36c71b9f4671eb7b0b1768',
    messagingSenderId: '797515232441',
    projectId: 'pawrescue-53d25',
    authDomain: 'pawrescue-53d25.firebaseapp.com',
    storageBucket: 'pawrescue-53d25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWP3Wrn2XfrI2jSRk5knrwRs_vo1VDN7c',
    appId: '1:797515232441:android:e6572495a30c00080b1768',
    messagingSenderId: '797515232441',
    projectId: 'pawrescue-53d25',
    storageBucket: 'pawrescue-53d25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTtKLVDp3a6xhfNe9ZlFF5v_Q4RwES3PM',
    appId: '1:797515232441:ios:c262ec8fb42bb86d0b1768',
    messagingSenderId: '797515232441',
    projectId: 'pawrescue-53d25',
    storageBucket: 'pawrescue-53d25.firebasestorage.app',
    iosBundleId: 'com.example.pawrescue1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTtKLVDp3a6xhfNe9ZlFF5v_Q4RwES3PM',
    appId: '1:797515232441:ios:c262ec8fb42bb86d0b1768',
    messagingSenderId: '797515232441',
    projectId: 'pawrescue-53d25',
    storageBucket: 'pawrescue-53d25.firebasestorage.app',
    iosBundleId: 'com.example.pawrescue1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCESl3dtJCTXM8UG3TWLXcNKCBHTD_F4P4',
    appId: '1:797515232441:web:e33c11c08d33080e0b1768',
    messagingSenderId: '797515232441',
    projectId: 'pawrescue-53d25',
    authDomain: 'pawrescue-53d25.firebaseapp.com',
    storageBucket: 'pawrescue-53d25.firebasestorage.app',
  );
}
